version: 1
module_version: 1.1.5

test_defaults:
  runner_image: jmfontaine/spacelift-runner-terraform:tf-wrapper
  environment:
    SPACELIFT_SKIP_TESTS_APPLY_AND_DESTROY: true
  before_init:
    - env

tests:
  - name: Set up in the default VPC
    project_root: examples/default-vpc
